const STORE_API='https://fpvgate-store.fpvgate-analytics.workers.dev';
const ANALYTICS_API='https://fpvgate-analytics.fpvgate-analytics.workers.dev';
const PASSWORD_HASH='fc4184b0cf53f0f30eb5ead285ae71b91addfa2c17c968f6b5a146a289c62e9c';
let adminToken='',currentFilter=null,ordersData=[],liveStatsInterval=null,currentEditImages=[],selectedOrderIds=new Set();

async function hashPassword(p){const e=new TextEncoder();const d=e.encode(p);const h=await crypto.subtle.digest('SHA-256',d);return Array.from(new Uint8Array(h)).map(b=>b.toString(16).padStart(2,'0')).join('')}
async function checkPassword(){const i=document.getElementById('password-input');const err=document.getElementById('auth-error');const h=await hashPassword(i.value);if(h===PASSWORD_HASH){adminToken=i.value;document.getElementById('auth-overlay').style.display='none';document.getElementById('main-content').style.display='flex';sessionStorage.setItem('fpvgate_admin_auth','true');sessionStorage.setItem('fpvgate_admin_token',i.value);loadDashboard()}else{err.style.display='block';i.value='';i.focus()}}
window.addEventListener('DOMContentLoaded',()=>{if(sessionStorage.getItem('fpvgate_admin_auth')==='true'){adminToken=sessionStorage.getItem('fpvgate_admin_token');document.getElementById('auth-overlay').style.display='none';document.getElementById('main-content').style.display='flex';loadDashboard()}else{document.getElementById('password-input').focus()}});

let currentEmailFilter=null;
function switchSection(name,btn){document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));document.getElementById('section-'+name).classList.add('active');if(btn)btn.classList.add('active');document.getElementById('sidebar').classList.remove('open');document.getElementById('sidebar-overlay').classList.remove('open');if(liveStatsInterval){clearInterval(liveStatsInterval);liveStatsInterval=null}if(name==='dashboard')loadDashboard();else if(name==='orders')loadOrders();else if(name==='livestats'){loadLiveStats();liveStatsInterval=setInterval(loadLiveStats,30000)}else if(name==='inventory')loadInventory();else if(name==='flasherstats')loadFlasherStats();else if(name==='emails')loadEmails()}
function toggleSidebar(){document.getElementById('sidebar').classList.toggle('open');document.getElementById('sidebar-overlay').classList.toggle('open')}

async function storeApi(path,method='GET',body=null){const o={method,headers:{'Authorization':`Bearer ${adminToken}`,'Content-Type':'application/json'}};if(body)o.body=JSON.stringify(body);const r=await fetch(`${STORE_API}${path}`,o);return r.json()}
async function analyticsApi(path){const r=await fetch(`${ANALYTICS_API}${path}`,{headers:{'Authorization':`Bearer ${adminToken}`}});return r.json()}

async function loadDashboard(){try{const d=await storeApi('/api/orders');const c={};(d.counts||[]).forEach(x=>c[x.status]=x.count);document.getElementById('dash-new').textContent=c['new']||0;document.getElementById('dash-label').textContent=c['label_created']||0;document.getElementById('dash-shipped').textContent=c['shipped']||0;document.getElementById('dash-completed').textContent=c['completed']||0}catch(e){}try{const l=await analyticsApi('/stats/live');document.getElementById('dash-viewers').textContent=l.total_active_viewers||0;document.getElementById('dash-store-visitors').textContent=l.active_store_visitors||0;document.getElementById('dash-cart-users').textContent=l.active_cart_users||0;document.getElementById('dash-conversion').textContent=(l.conversion_rate_30d||'0.00')+'%'}catch(e){}try{const inv=await storeApi('/api/inventory');const low=(inv.products||[]).filter(p=>p.stock_quantity<=p.low_stock_threshold).length;const b=document.getElementById('low-stock-badge');if(low>0){b.textContent=low;b.style.display='inline'}else b.style.display='none'}catch(e){}}

async function loadOrders(){const ld=document.getElementById('orders-loading'),tb=document.getElementById('orders-table'),em=document.getElementById('orders-empty');ld.style.display='block';tb.style.display='none';em.style.display='none';try{let p='';if(currentFilter==='archived')p='?archived=1';else if(currentFilter)p=`?status=${currentFilter}`;const d=await storeApi(`/api/orders${p}`);ordersData=d.orders||[];const m={};(d.counts||[]).forEach(c=>m[c.status]=c.count);document.getElementById('count-new').textContent=m['new']||0;document.getElementById('count-label').textContent=m['label_created']||0;document.getElementById('count-shipped').textContent=m['shipped']||0;document.getElementById('count-completed').textContent=m['completed']||0;renderOrders(ordersData);ld.style.display='none';if(ordersData.length===0)em.style.display='block';else tb.style.display='table'}catch(e){ld.innerHTML=`<div class="error-text">Failed to load orders: ${e.message}</div>`}}
const LABEL_COLORS={'urgent':'#e53e3e','priority':'#ed8936','vip':'#9f7aea','gift':'#d53f8c','wholesale':'#38b2ac','preorder':'#4299e1','international':'#667eea','issue':'#f56565','custom':'#718096','review':'#ecc94b'};
function labelColor(l){return LABEL_COLORS[l.toLowerCase()]||'#718096'}
function renderLabelPills(labels){if(!labels||!labels.length)return'';return labels.map(l=>`<span class="order-label" style="background:${labelColor(l)}">${escHtml(l)}</span>`).join('')}
function renderOrders(orders){selectedOrderIds.clear();updateBulkBar();const tb=document.getElementById('orders-body');tb.innerHTML='';const sa=document.getElementById('select-all');if(sa)sa.checked=false;orders.forEach(o=>{const tr=document.createElement('tr');tr.className='clickable';const ic=Array.isArray(o.items)?o.items.reduce((s,i)=>s+(i.quantity||1),0):'-';const dt=new Date(o.created_at).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});tr.innerHTML=`<td onclick="event.stopPropagation()"><input type="checkbox" class="order-cb" data-id="${o.id}" onchange="toggleOrderSelect(${o.id},this.checked)"></td><td><strong>#${o.invoice_number||o.id}</strong></td><td>${dt}</td><td>${escHtml(o.customer_name)}</td><td>${ic}</td><td>&pound;${parseFloat(o.total).toFixed(2)}</td><td>${renderLabelPills(o.labels)}</td><td><span class="status-badge status-${o.status}">${formatStatus(o.status)}</span></td><td>${o.tracking_number?escHtml(o.tracking_number):'-'}</td>`;tr.onclick=()=>openDetail(o.id);tb.appendChild(tr)})}
function toggleOrderSelect(id,checked){if(checked)selectedOrderIds.add(id);else selectedOrderIds.delete(id);updateBulkBar()}
function toggleSelectAll(checked){document.querySelectorAll('.order-cb').forEach(cb=>{cb.checked=checked;const id=parseInt(cb.dataset.id);if(checked)selectedOrderIds.add(id);else selectedOrderIds.delete(id)});updateBulkBar()}
function updateBulkBar(){const bar=document.getElementById('bulk-bar');const cnt=document.getElementById('bulk-count');if(!bar)return;if(selectedOrderIds.size>0){bar.style.display='flex';cnt.textContent=selectedOrderIds.size+' selected'}else{bar.style.display='none'}}
function clearSelection(){selectedOrderIds.clear();document.querySelectorAll('.order-cb').forEach(cb=>cb.checked=false);const sa=document.getElementById('select-all');if(sa)sa.checked=false;updateBulkBar()}
async function bulkAddLabel(){const l=prompt('Enter label to add to '+selectedOrderIds.size+' orders:');if(!l)return;const label=l.trim().toLowerCase();for(const id of selectedOrderIds){const order=ordersData.find(o=>o.id===id);const existing=order?.labels||[];if(!existing.includes(label)){await storeApi(`/api/orders/${id}/labels`,'PUT',{labels:[...existing,label]})}}clearSelection();loadOrders()}
async function bulkArchive(archive){const action=archive?'archive':'unarchive';if(!confirm(`${action.charAt(0).toUpperCase()+action.slice(1)} ${selectedOrderIds.size} orders?`))return;for(const id of selectedOrderIds){await storeApi(`/api/orders/${id}/archive`,'POST',{archived:archive})}clearSelection();loadOrders()}
function filterOrders(s,btn){currentFilter=s;document.querySelectorAll('.filter-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');loadOrders()}
let currentDetailOrderLabels=[];
let currentDetailOrderId=null;
async function addLabel(id){const l=prompt('Enter label name (e.g. urgent, priority, vip, gift, wholesale, preorder, international, issue):');if(!l)return;const labels=[...currentDetailOrderLabels,l.trim().toLowerCase()];const unique=[...new Set(labels)];try{await storeApi(`/api/orders/${id}/labels`,'PUT',{labels:unique});openDetail(id);loadOrders()}catch(e){alert('Failed: '+e.message)}}
async function removeLabel(id,label){const labels=currentDetailOrderLabels.filter(l=>l!==label);try{await storeApi(`/api/orders/${id}/labels`,'PUT',{labels});openDetail(id);loadOrders()}catch(e){alert('Failed: '+e.message)}}
async function archiveOrder(id,archive){if(archive&&!confirm('Archive this order? It will be hidden from the main list.'))return;try{await storeApi(`/api/orders/${id}/archive`,'POST',{archived:archive});closeDetail();loadOrders()}catch(e){alert('Failed: '+e.message)}}
async function openDetail(id){const p=document.getElementById('detail-panel'),ov=document.getElementById('detail-overlay'),c=document.getElementById('detail-content');p.classList.add('open');ov.classList.add('open');c.innerHTML='<div class="loading"><div class="spinner"></div>Loading...</div>';try{const o=await storeApi(`/api/orders/${id}`);const cm=await storeApi(`/api/orders/${id}/comments`);const rf=await storeApi(`/api/orders/${id}/refunds`);const tk=await storeApi(`/api/orders/${id}/tracking`);const rt=await storeApi(`/api/orders/${id}/return`);document.getElementById('detail-title').textContent=`Order #${o.invoice_number||o.id}`;c.innerHTML=renderDetail(o,cm.comments||[],rf.refunds||[],tk.events||[],rt.return||null)}catch(e){c.innerHTML=`<div class="error-text">Failed: ${e.message}</div>`}}
function closeDetail(){document.getElementById('detail-panel').classList.remove('open');document.getElementById('detail-overlay').classList.remove('open')}
function renderDetail(o,comments,refunds,trackingEvents,returnData){const a=o.shipping_address||{},items=Array.isArray(o.items)?o.items:[],dt=new Date(o.created_at).toLocaleString('en-GB'),tr=refunds.reduce((s,r)=>s+r.amount,0);
currentDetailOrderLabels=o.labels||[];currentDetailOrderId=o.id;
let h=`<div class="detail-section"><h3>Order Info</h3><div class="detail-row"><span class="label">Status</span><span class="value"><span class="status-badge status-${o.status}">${formatStatus(o.status)}</span></span></div><div class="detail-row"><span class="label">Date</span><span class="value">${dt}</span></div><div class="detail-row"><span class="label">Email</span><span class="value">${escHtml(o.customer_email)}</span></div><div class="detail-row"><span class="label">Shipping Method</span><span class="value">${escHtml(o.shipping_method||'N/A')}</span></div><div class="detail-row"><span class="label">Labels</span><span class="value" style="display:flex;flex-wrap:wrap;gap:4px;align-items:center">${(o.labels||[]).map(l=>`<span class="order-label" style="background:${labelColor(l)};cursor:pointer" onclick="removeLabel(${o.id},'${l}')" title="Click to remove">${escHtml(l)} &times;</span>`).join('')}<button class="btn btn-sm btn-secondary" onclick="addLabel(${o.id})" style="padding:2px 8px;font-size:11px">+ Add</button></span></div></div>`;
h+=`<div class="detail-section"><h3>Shipping Address</h3><div style="font-size:14px;line-height:1.6">${escHtml(a.name||o.customer_name)}<br>${a.company?escHtml(a.company)+'<br>':''}${escHtml(a.address1||'')}<br>${a.address2?escHtml(a.address2)+'<br>':''}${escHtml(a.city||'')}${a.province?', '+escHtml(a.province):''}<br>${escHtml(a.postalCode||'')}<br>${escHtml(a.country||'')}${a.phone?'<br>'+escHtml(a.phone):''}</div></div>`;
h+=`<div class="detail-section"><h3>Items</h3>${items.map(i=>`<div class="item-row"><span>${escHtml(i.name)} x${i.quantity}</span><span>&pound;${parseFloat(i.totalPrice||i.price*i.quantity).toFixed(2)}</span></div>`).join('')}<div class="item-row" style="border-top:1px solid #e2e8f0;margin-top:8px;padding-top:8px"><span>Shipping</span><span>&pound;${parseFloat(o.shipping_fees||0).toFixed(2)}</span></div><div class="item-row" style="font-weight:700;font-size:16px"><span>Total</span><span>&pound;${parseFloat(o.total).toFixed(2)}</span></div>${tr>0?`<div class="item-row" style="color:#e53e3e"><span>Total Refunded</span><span>-&pound;${tr.toFixed(2)}</span></div>`:''}</div>`;
if(o.label_url||o.tracking_number){h+=`<div class=\"detail-section\"><h3>Shipping Label</h3><div class=\"detail-row\"><span class=\"label\">Tracking</span><span class=\"value\">${escHtml(o.tracking_number||'N/A')} <button class=\"btn btn-sm btn-secondary\" onclick=\"setManualTracking(${o.id})\" style=\"padding:2px 8px;font-size:11px;margin-left:8px\">Edit</button></span></div>`;if(o.label_url)h+=`<div style=\"margin-top:8px\"><a href=\"${escHtml(o.label_url)}\" target=\"_blank\" class=\"label-link\">View / Print Label (PDF)</a></div>`;h+=`</div>`}
if(trackingEvents&&trackingEvents.length>0){h+=`<div class="detail-section"><h3>Tracking Timeline</h3><div class="tracking-timeline">`;trackingEvents.forEach((evt,i)=>{const isLast=i===trackingEvents.length-1;const statusCls={'DELIVERED':'tracking-delivered','TRANSIT':'tracking-transit','PRE_TRANSIT':'tracking-pre','RETURNED':'tracking-returned','FAILURE':'tracking-failure'}[evt.status]||'tracking-unknown';const loc=[evt.location_city,evt.location_state,evt.location_country].filter(Boolean).join(', ');const evtDate=evt.status_date?new Date(evt.status_date).toLocaleString('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'';h+=`<div class="tracking-event${isLast?' tracking-latest':''}"><div class="tracking-dot ${statusCls}"></div><div class="tracking-line"></div><div class="tracking-info"><div class="tracking-status-row"><span class="tracking-badge ${statusCls}">${escHtml(evt.status)}</span><span class="tracking-date">${evtDate}</span></div><div class="tracking-details">${escHtml(evt.status_details||evt.substatus_text||'')}</div>${loc?`<div class="tracking-location">${escHtml(loc)}</div>`:''}</div></div>`});h+=`</div></div>`}
if(refunds.length>0){h+=`<div class="detail-section"><h3>Refund History</h3>`;refunds.forEach(r=>{const rd=new Date(r.created_at).toLocaleString('en-GB');h+=`<div class="detail-row"><span class="label">&pound;${r.amount.toFixed(2)}${r.comment?' - '+escHtml(r.comment):''}</span><span class="value" style="font-size:12px;color:#a0aec0">${rd}</span></div>`});h+=`</div>`}
h+=`<div class="detail-section"><h3>Comments</h3><div class="comment-list" id="cl-${o.id}">`;if(comments.length===0)h+='<div style="color:#a0aec0;font-size:13px">No comments yet</div>';comments.forEach(c=>{const cd=new Date(c.created_at).toLocaleString('en-GB');h+=`<div class="comment-item">${escHtml(c.comment)}<div class="comment-date">${cd}</div></div>`});h+=`</div><div class="comment-input-row"><input type="text" id="ci-${o.id}" placeholder="Add a comment..." onkeypress="if(event.key==='Enter')addComment(${o.id})"><button class="btn btn-sm btn-primary" onclick="addComment(${o.id})">Post</button></div></div>`;
// Return section
if(returnData){const rs=returnData;const rStatusLabels={requested:'Requested',label_created:'Label Created',in_transit:'In Transit',received:'Received',refunded:'Refunded',cancelled:'Cancelled'};const rStatusCls={requested:'status-new',label_created:'status-label_created',in_transit:'status-shipped',received:'status-completed',refunded:'status-refunded',cancelled:'status-cancelled'};h+=`<div class="detail-section"><h3>Return</h3><div class="detail-row"><span class="label">Status</span><span class="value"><span class="status-badge ${rStatusCls[rs.status]||''}">${rStatusLabels[rs.status]||rs.status}</span></span></div>`;if(rs.reason)h+=`<div class="detail-row"><span class="label">Reason</span><span class="value">${escHtml(rs.reason)}</span></div>`;if(rs.refund_amount)h+=`<div class="detail-row"><span class="label">Refund Amount</span><span class="value">&pound;${parseFloat(rs.refund_amount).toFixed(2)}</span></div>`;if(rs.tracking_number)h+=`<div class="detail-row"><span class="label">Return Tracking</span><span class="value">${escHtml(rs.tracking_number)}</span></div>`;if(rs.label_url)h+=`<div style="margin-top:8px"><a href="${escHtml(rs.label_url)}" target="_blank" class="label-link">View Return Label (PDF)</a></div>`;h+=`<div style="margin-top:12px;display:flex;gap:8px;flex-wrap:wrap">`;if(rs.status==='requested')h+=`<button class="btn btn-primary btn-sm" onclick="fetchReturnRates(${o.id})">Get Return Rates</button><button class="btn btn-secondary btn-sm" onclick="updateReturnStatus(${o.id},'cancelled')">Cancel Return</button>`;if(rs.status==='received')h+=`<button class="btn btn-success btn-sm" onclick="updateReturnStatus(${o.id},'refunded')">Process Refund</button>`;if(rs.status==='in_transit')h+=`<button class="btn btn-secondary btn-sm" onclick="updateReturnStatus(${o.id},'received')">Mark Received</button>`;if(rs.status==='label_created')h+=`<button class="btn btn-secondary btn-sm" onclick="updateReturnStatus(${o.id},'in_transit')">Mark In Transit</button><button class="btn btn-secondary btn-sm" onclick="updateReturnStatus(${o.id},'received')">Mark Received</button>`;h+=`</div></div>`}
h+=`<div class="action-bar">`;if(!o.label_url&&o.status!=='cancelled'&&o.status!=='refunded'){h+=`<button class="btn btn-secondary" onclick="triggerLabelUpload(${o.id})">Upload Label PDF</button><input type="file" id="label-file-${o.id}" accept="application/pdf" style="display:none" onchange="uploadLabelFile(${o.id})">`;if(!o.tracking_number){h+=`<button class="btn btn-primary" onclick="fetchRates(${o.id})">Create Shipping Label</button>`;h+=`<button class="btn btn-secondary" onclick="setManualTracking(${o.id})">Set Tracking Number</button>`}}if(o.status==='label_created')h+=`<button class="btn btn-success" onclick="updateStatus(${o.id},'shipped')">Mark as Shipped</button>`;if(o.status==='shipped')h+=`<button class="btn btn-secondary" onclick="updateStatus(${o.id},'completed')">Mark as Completed</button>`;if(o.status!=='cancelled'&&o.status!=='refunded'){h+=`<button class="btn btn-danger" onclick="toggleRefund(${o.id})">Issue Refund</button>`;if((o.status==='shipped'||o.status==='completed')&&!returnData)h+=`<button class="btn btn-secondary" onclick="initiateReturn(${o.id})">Initiate Return</button>`;h+=`<button class="btn btn-secondary" onclick="confirmCancel(${o.id})">Cancel Order</button>`}if(o.archived)h+=`<button class="btn btn-secondary" onclick="archiveOrder(${o.id},false)">Unarchive</button>`;else h+=`<button class="btn btn-secondary" onclick="archiveOrder(${o.id},true)">Archive</button>`;h+=`</div>`;
h+=`<div class=\"detail-section\"><h3>Customer Emails</h3><div style=\"display:flex;gap:8px;flex-wrap:wrap\"><button class=\"btn btn-sm btn-secondary\" onclick=\"sendOrderEmail(${o.id},'tracking')\">${o.tracking_number?'Send Tracking Email':'No Tracking Set'}</button><button class=\"btn btn-sm btn-secondary\" onclick=\"sendOrderEmail(${o.id},'shipped')\">Send Shipped Email</button><button class=\"btn btn-sm btn-secondary\" onclick=\"sendOrderEmail(${o.id},'confirmation')\">Resend Confirmation</button></div></div>`;
h+=`<div class="refund-form" id="rf-${o.id}"><label>Refund Amount (&pound;)</label><input type="number" id="ra-${o.id}" step="0.01" min="0.01" max="${o.total}" value="${o.total}"><label>Reason (optional)</label><textarea id="rr-${o.id}" placeholder="Reason for refund..."></textarea><div id="re-${o.id}" class="error-text" style="margin-bottom:8px"></div><div style="display:flex;gap:8px"><button class="btn btn-danger" onclick="submitRefund(${o.id})">Confirm Refund</button><button class="btn btn-secondary" onclick="toggleRefund(${o.id})">Cancel</button></div></div>`;
h+=`<div id="rates-container"></div>`;return h}

async function addComment(id){const i=document.getElementById(`ci-${id}`);const t=i.value.trim();if(!t)return;i.disabled=true;try{await storeApi(`/api/orders/${id}/comments`,'POST',{comment:t});openDetail(id)}catch(e){alert('Failed: '+e.message)}i.disabled=false}
function toggleRefund(id){document.getElementById(`rf-${id}`).classList.toggle('open')}
async function submitRefund(id){const amt=parseFloat(document.getElementById(`ra-${id}`).value);const cmt=document.getElementById(`rr-${id}`).value.trim();const err=document.getElementById(`re-${id}`);err.textContent='';if(!amt||amt<=0){err.textContent='Enter a valid amount';return}try{const r=await storeApi(`/api/orders/${id}/refund`,'POST',{amount:amt,comment:cmt});if(r.error){err.textContent=r.error;return}openDetail(id);loadOrders()}catch(e){err.textContent='Failed: '+e.message}}
async function confirmCancel(id){if(!confirm('Are you sure you want to cancel this order? This will issue a full refund and restore inventory.'))return;try{const r=await storeApi(`/api/orders/${id}/cancel`,'POST');if(r.error){alert(r.error);return}closeDetail();loadOrders()}catch(e){alert('Failed: '+e.message)}}
async function fetchRates(id){const c=document.getElementById('rates-container');c.innerHTML='<div class="loading"><div class="spinner"></div>Fetching rates...</div>';try{const d=await storeApi(`/api/orders/${id}/rates`,'POST');if(!d.rates||d.rates.length===0){c.innerHTML='<div class="error-text">No rates available.</div>';return}let h='<div class="detail-section" style="margin-top:20px"><h3>Select Shipping Service</h3>';d.rates.forEach(r=>{h+=`<div class="rate-option" onclick="purchaseLabel(${id},'${r.objectId}')"><div><div class="rate-name">${escHtml(r.provider)} - ${escHtml(r.serviceName)}</div><div class="rate-days">${r.estimatedDays?r.estimatedDays+' day(s)':''} ${escHtml(r.durationTerms)}</div></div><div class="rate-price">&pound;${parseFloat(r.amount).toFixed(2)}</div></div>`});h+='</div>';c.innerHTML=h}catch(e){c.innerHTML=`<div class="error-text">Failed: ${e.message}</div>`}}
async function purchaseLabel(id,rateId){const c=document.getElementById('rates-container');c.innerHTML='<div class="loading"><div class="spinner"></div>Purchasing label...</div>';try{const d=await storeApi(`/api/orders/${id}/label`,'POST',{rateId});if(d.error){c.innerHTML=`<div class="error-text">${escHtml(d.error)}</div>`;return}c.innerHTML=`<div class="detail-section" style="margin-top:20px"><h3 class="success-text">Label Created</h3><div class="detail-row"><span class="label">Tracking</span><span class="value">${escHtml(d.trackingNumber)}</span></div><div style="margin-top:12px"><a href="${escHtml(d.labelUrl)}" target="_blank" class="btn btn-primary">View / Print Label</a></div></div>`;loadOrders()}catch(e){c.innerHTML=`<div class="error-text">Failed: ${e.message}</div>`}}
async function updateStatus(id,s){try{await storeApi(`/api/orders/${id}/status`,'PUT',{status:s});closeDetail();loadOrders()}catch(e){alert('Failed: '+e.message)}}
async function setManualTracking(id){const tn=prompt('Enter tracking number:');if(!tn)return;const trimmed=tn.trim();if(!trimmed)return;try{await storeApi(`/api/orders/${id}/status`,'PUT',{status:'label_created',trackingNumber:trimmed});openDetail(id);loadOrders()}catch(e){alert('Failed: '+e.message)}}
function triggerLabelUpload(id){document.getElementById('label-file-'+id).click()}
async function uploadLabelFile(id){const file=document.getElementById('label-file-'+id).files[0];if(!file)return;const c=document.getElementById('rates-container');c.innerHTML='<div class="loading"><div class="spinner"></div>Uploading label...</div>';const fd=new FormData();fd.append('label',file);try{const r=await fetch(`${STORE_API}/api/orders/${id}/upload-label`,{method:'POST',headers:{'Authorization':`Bearer ${adminToken}`},body:fd});const d=await r.json();if(d.error){c.innerHTML=`<div class="error-text">${escHtml(d.error)}</div>`;return}openDetail(id);loadOrders()}catch(e){c.innerHTML=`<div class="error-text">Failed: ${e.message}</div>`}}
async function sendOrderEmail(id,type){const btn=event.target;btn.disabled=true;btn.textContent='Sending...';try{const r=await storeApi(`/api/orders/${id}/send-email`,'POST',{type});if(r.error){alert(r.error);return}alert('Email sent to '+r.sentTo)}catch(e){alert('Failed: '+e.message)}finally{btn.disabled=false;openDetail(id)}}
async function initiateReturn(id){const reason=prompt('Reason for return:');if(reason===null)return;try{const r=await storeApi(`/api/orders/${id}/return`,'POST',{reason});if(r.error){alert(r.error);return}openDetail(id)}catch(e){alert('Failed: '+e.message)}}
async function fetchReturnRates(id){const c=document.getElementById('rates-container');c.innerHTML='<div class="loading"><div class="spinner"></div>Fetching return rates...</div>';try{const d=await storeApi(`/api/orders/${id}/return/rates`,'POST');if(!d.rates||d.rates.length===0){c.innerHTML='<div class="error-text">No return rates available.</div>';return}let h='<div class="detail-section" style="margin-top:20px"><h3>Select Return Shipping Service</h3>';d.rates.forEach(r=>{h+=`<div class="rate-option" onclick="purchaseReturnLabel(${id},'${r.objectId}')"><div><div class="rate-name">${escHtml(r.provider)} - ${escHtml(r.serviceName)}</div><div class="rate-days">${r.estimatedDays?r.estimatedDays+' day(s)':''} ${escHtml(r.durationTerms)}</div></div><div class="rate-price">&pound;${parseFloat(r.amount).toFixed(2)}</div></div>`});h+='</div>';c.innerHTML=h}catch(e){c.innerHTML=`<div class="error-text">Failed: ${e.message}</div>`}}
async function purchaseReturnLabel(id,rateId){const c=document.getElementById('rates-container');c.innerHTML='<div class="loading"><div class="spinner"></div>Purchasing return label...</div>';try{const d=await storeApi(`/api/orders/${id}/return/label`,'POST',{rateId});if(d.error){c.innerHTML=`<div class="error-text">${escHtml(d.error)}</div>`;return}c.innerHTML=`<div class="detail-section" style="margin-top:20px"><h3 class="success-text">Return Label Created</h3><div class="detail-row"><span class="label">Return Tracking</span><span class="value">${escHtml(d.trackingNumber)}</span></div><div style="margin-top:12px"><a href="${escHtml(d.labelUrl)}" target="_blank" class="btn btn-primary">View Return Label</a></div><p style="margin-top:8px;font-size:13px;color:#718096">Return label has been emailed to the customer.</p></div>`;loadOrders()}catch(e){c.innerHTML=`<div class="error-text">Failed: ${e.message}</div>`}}
async function updateReturnStatus(id,s){const confirmMsg=s==='refunded'?'Process refund and restore inventory for this return?':`Update return status to "${s}"?`;if(!confirm(confirmMsg))return;try{const r=await storeApi(`/api/orders/${id}/return/status`,'PUT',{status:s});if(r.error){alert(r.error);return}openDetail(id);loadOrders()}catch(e){alert('Failed: '+e.message)}}
async function loadLiveStats(){try{const d=await analyticsApi('/stats/live');document.getElementById('live-total-viewers').textContent=d.total_active_viewers||0;document.getElementById('live-store-visitors').textContent=d.active_store_visitors||0;document.getElementById('live-cart-users').textContent=d.active_cart_users||0;document.getElementById('live-conversion').textContent=(d.conversion_rate_30d||'0.00')+'%';document.getElementById('live-conversion-detail').textContent=`${d.orders_30d||0} orders / ${d.store_visitors_30d||0} store visitors`;const gt=document.getElementById('geo-table');document.getElementById('geo-loading').style.display='none';const geo=d.geo_breakdown||[];if(geo.length===0)gt.innerHTML='<div style="color:#a0aec0;padding:20px;text-align:center">No visitor data yet</div>';else gt.innerHTML=geo.map(g=>`<div class="country-row"><div class="country-name"><span class="country-flag">${countryFlag(g.country)}</span><span>${g.country}</span></div><span>${g.visitors} visitor${g.visitors!==1?'s':''}</span></div>`).join('');gt.style.display='block';const hb=document.getElementById('hourly-body');document.getElementById('hourly-loading').style.display='none';const ht=document.getElementById('hourly-table');const hr=d.hourly_activity||[];if(hr.length===0)hb.innerHTML='<tr><td colspan="4" style="text-align:center;color:#a0aec0">No activity data</td></tr>';else hb.innerHTML=hr.map(h=>{const hour=h.hour.split(' ')[1]||h.hour;return`<tr><td>${hour}</td><td>${h.unique_visitors}</td><td>${h.store_views}</td><td>${h.cart_adds}</td></tr>`}).join('');ht.style.display='table'}catch(e){console.error('Live stats failed:',e);document.getElementById('geo-loading').innerHTML='<div class="error-text">Failed to load live stats</div>'}}

async function loadInventory(){const ld=document.getElementById('inventory-loading'),tb=document.getElementById('inventory-table'),em=document.getElementById('inventory-empty');ld.style.display='block';tb.style.display='none';em.style.display='none';try{const d=await storeApi('/api/inventory');const pr=d.products||[];ld.style.display='none';if(pr.length===0){em.style.display='block';return}tb.style.display='table';const bd=document.getElementById('inventory-body');bd.innerHTML='';let lc=0;pr.forEach(p=>{const low=p.stock_quantity<=p.low_stock_threshold;if(low)lc++;const tr=document.createElement('tr');const archived=!p.active;tr.style.opacity=archived?'0.5':'1';tr.innerHTML=`<td><strong>${escHtml(p.product_name)}</strong><br><span style="font-size:11px;color:#a0aec0">${escHtml(p.product_id)}</span></td><td>${escHtml(p.sku||'-')}</td><td><div class="stock-edit-row"><input type="number" id="si-${p.product_id}" value="${p.stock_quantity}" min="0"><button class="btn btn-sm btn-primary" onclick="saveStock('${escHtml(p.product_id)}')">Save</button></div>${low?'<div style="color:#e53e3e;font-size:11px;margin-top:4px">Low stock</div>':''}</td><td>${p.low_stock_threshold}</td><td><button class="btn btn-sm btn-secondary" onclick="editProduct('${escHtml(p.product_id)}')">Edit</button> <button class="btn btn-sm btn-secondary" onclick="viewLog('${escHtml(p.product_id)}','${escHtml(p.product_name)}')">History</button> <button class="btn btn-sm ${archived?'btn-success':'btn-secondary'}" onclick="archiveProduct('${escHtml(p.product_id)}',${archived})">${archived?'Restore':'Archive'}</button> <button class="btn btn-sm btn-danger" onclick="deleteProduct('${escHtml(p.product_id)}','${escHtml(p.product_name)}')">Delete</button></td>`;bd.appendChild(tr)});const b=document.getElementById('low-stock-badge');if(lc>0){b.textContent=lc;b.style.display='inline'}else b.style.display='none'}catch(e){ld.innerHTML=`<div class="error-text">Failed: ${e.message}</div>`}}
async function saveStock(pid){const q=parseInt(document.getElementById(`si-${pid}`).value);const reason=prompt('Reason for stock change (optional):')||'Manual adjustment';try{const r=await storeApi(`/api/inventory/${encodeURIComponent(pid)}`,'PUT',{stock_quantity:q,reason});if(r.error){alert(r.error);return}loadInventory()}catch(e){alert('Failed: '+e.message)}}
async function viewLog(pid,name){const card=document.getElementById('stock-log-card'),ct=document.getElementById('stock-log-content');document.getElementById('stock-log-title').textContent='Stock History: '+name;card.style.display='block';ct.innerHTML='<div class="loading"><div class="spinner"></div>Loading...</div>';try{const d=await storeApi(`/api/inventory/${encodeURIComponent(pid)}/log`);const log=d.log||[];if(log.length===0){ct.innerHTML='<div style="color:#a0aec0;text-align:center;padding:20px">No changes recorded</div>';return}ct.innerHTML=log.map(l=>{const dt=new Date(l.created_at).toLocaleString('en-GB');const cls=l.change_amount>=0?'log-change-pos':'log-change-neg';const sign=l.change_amount>=0?'+':'';return`<div class="log-entry"><div><span class="${cls}">${sign}${l.change_amount}</span> - ${escHtml(l.reason||'No reason')}</div><div class="log-date">${dt}</div></div>`}).join('')}catch(e){ct.innerHTML=`<div class="error-text">Failed: ${e.message}</div>`}}
function openAddProductModal(){document.getElementById('add-product-modal').classList.add('open')}
function closeAddProductModal(){document.getElementById('add-product-modal').classList.remove('open');document.getElementById('add-product-error').textContent=''}
async function addProduct(){const id=document.getElementById('new-product-id').value.trim(),nm=document.getElementById('new-product-name').value.trim(),sk=document.getElementById('new-product-sku').value.trim(),pr=parseFloat(document.getElementById('new-product-price').value)||0,desc=document.getElementById('new-product-desc').value.trim(),sdesc=document.getElementById('new-product-short-desc').value.trim(),ldesc=document.getElementById('new-product-long-desc').value.trim(),img=document.getElementById('new-product-image').value.trim(),st=parseInt(document.getElementById('new-product-stock').value)||0,th=parseInt(document.getElementById('new-product-threshold').value)||5,err=document.getElementById('add-product-error');err.textContent='';if(!id||!nm){err.textContent='Product ID and Name are required';return}if(!pr){err.textContent='Price is required';return}try{const r=await storeApi('/api/inventory','POST',{product_id:id,product_name:nm,sku:sk||null,price:pr,description:desc||null,short_description:sdesc||null,long_description:ldesc||null,image_url:img||null,stock_quantity:st,low_stock_threshold:th});if(r.error){err.textContent=r.error;return}closeAddProductModal();loadInventory()}catch(e){err.textContent='Failed: '+e.message}}
let flasherCharts={};let flasherDateRange=7;
function setFlasherDateFilter(days,btn){flasherDateRange=days;document.querySelectorAll('#section-flasherstats .filter-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');loadFlasherStats()}
async function loadFlasherStats(){const ld=document.getElementById('flasher-loading'),ct=document.getElementById('flasher-content');ld.style.display='block';ct.style.display='none';try{const r=await fetch(`${ANALYTICS_API}/stats/detailed`);const data=await r.json();const fd=flasherDateRange==='all'?data:(()=>{const now=new Date();const cut=new Date();cut.setDate(now.getDate()-flasherDateRange);if(data.recent_activity)data.recent_activity=data.recent_activity.filter(i=>new Date(i.date)>=cut);return data})();renderFlasherStats(fd);ld.style.display='none';ct.style.display='block'}catch(e){ld.innerHTML=`<div class="error-text">Failed to load: ${e.message}</div>`}}
function renderFlasherStats(d){document.getElementById('fl-total-events').textContent=(d.total_events||0).toLocaleString();document.getElementById('fl-unique-users').textContent=(d.unique_users_30d||0).toLocaleString();document.getElementById('fl-new-users').textContent=(d.new_users_30d||0).toLocaleString();document.getElementById('fl-returning-users').textContent=(d.returning_users_30d||0).toLocaleString();if(d.success_rate){document.getElementById('fl-success-rate').textContent=d.success_rate.rate;document.getElementById('fl-total-flashes').textContent=(d.success_rate.successes||0).toLocaleString()}createFlWorldMap(d.country_stats||[]);createFlActivityChart(d.recent_activity||[]);createFlBoardChart(d.board_stats||[]);createFlVersionChart(d.version_stats||[]);createFlFlashChart(d.flash_events||[]);createFlRecencyChart(d.users_by_recency||[]);renderFlErrorTable(d.common_errors||[])}
async function createFlWorldMap(countries){const ctx=document.getElementById('fl-world-map');if(flasherCharts.map)flasherCharts.map.destroy();try{const r=await fetch('https://unpkg.com/world-atlas@2/countries-110m.json');const w=await r.json();const feat=ChartGeo.topojson.feature(w,w.objects.countries).features;const iso={'840':'US','826':'GB','124':'CA','036':'AU','276':'DE','250':'FR','528':'NL','380':'IT','724':'ES','752':'SE','578':'NO','208':'DK','246':'FI','616':'PL','203':'CZ','056':'BE','040':'AT','756':'CH','372':'IE','554':'NZ','392':'JP','410':'KR','156':'CN','356':'IN','076':'BR','484':'MX','032':'AR','702':'SG','344':'HK','158':'TW'};const cm={};countries.forEach(c=>cm[c.country]=c.count);const mx=Math.max(...countries.map(c=>c.count),1);const dv=feat.map(f=>({feature:f,value:cm[iso[f.id]]||0}));flasherCharts.map=new Chart(ctx,{type:'choropleth',data:{labels:feat.map(d=>d.properties.name),datasets:[{label:'Users',data:dv,backgroundColor:c=>{if(c.dataIndex===undefined)return'#e2e8f0';const v=c.dataset.data[c.dataIndex].value;if(v===0)return'#e2e8f0';const i=Math.min(v/mx,1);return`rgb(${Math.floor(226-160*i)},${Math.floor(232-79*i)},${Math.floor(240-15*i)})`},borderColor:'#cbd5e0',borderWidth:0.5}]},options:{responsive:true,maintainAspectRatio:false,showOutline:true,showGraticule:false,plugins:{legend:{display:false},tooltip:{callbacks:{title:t=>{const f=t[0].raw.feature;return f&&f.properties?f.properties.name:'Unknown'},label:c=>c.raw.value>0?`Users: ${c.raw.value}`:'No data'}}},scales:{projection:{axis:'x',projection:'equalEarth'}}}})}catch(e){ctx.parentElement.innerHTML='<div style="padding:40px;text-align:center;color:#a0aec0">Unable to load map</div>'}}
function createFlActivityChart(data){const ctx=document.getElementById('fl-activity-chart');if(flasherCharts.activity)flasherCharts.activity.destroy();data.sort((a,b)=>new Date(a.date)-new Date(b.date));flasherCharts.activity=new Chart(ctx,{type:'line',data:{labels:data.map(i=>i.date),datasets:[{label:'Events',data:data.map(i=>i.count),borderColor:'#4299e1',backgroundColor:'rgba(66,153,225,0.1)',fill:true,tension:0.3,pointRadius:3,borderWidth:2}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,grid:{color:'#e2e8f0'}},x:{grid:{display:false}}}}})}
function createFlBoardChart(data){const ctx=document.getElementById('fl-board-chart');if(flasherCharts.board)flasherCharts.board.destroy();flasherCharts.board=new Chart(ctx,{type:'doughnut',data:{labels:data.map(i=>i.board),datasets:[{data:data.map(i=>i.count),backgroundColor:['#4299e1','#48bb78','#ed8936','#9f7aea','#f56565']}]},options:{responsive:true,plugins:{legend:{position:'bottom',labels:{padding:15,font:{size:12}}}}}})}
function createFlVersionChart(data){const ctx=document.getElementById('fl-version-chart');if(flasherCharts.version)flasherCharts.version.destroy();flasherCharts.version=new Chart(ctx,{type:'doughnut',data:{labels:data.map(i=>i.version),datasets:[{data:data.map(i=>i.count),backgroundColor:['#4299e1','#48bb78','#ed8936','#9f7aea','#f56565','#38b2ac','#f687b3']}]},options:{responsive:true,plugins:{legend:{position:'bottom',labels:{padding:15,font:{size:12}}}}}})}
function createFlFlashChart(data){const ctx=document.getElementById('fl-flash-events-chart');if(flasherCharts.flash)flasherCharts.flash.destroy();flasherCharts.flash=new Chart(ctx,{type:'bar',data:{labels:data.map(i=>i.event_name.replace('flash_','').replace('_',' ')),datasets:[{label:'Count',data:data.map(i=>i.count),backgroundColor:data.map(i=>i.event_name==='flash_complete'?'#48bb78':i.event_name==='flash_failed'?'#f56565':'#4299e1')}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,grid:{color:'#e2e8f0'}},x:{grid:{display:false}}}}})}
function createFlRecencyChart(data){const ctx=document.getElementById('fl-recency-chart');if(flasherCharts.recency)flasherCharts.recency.destroy();const order=['last_day','last_week','last_month','older'];const labels={last_day:'Last 24h',last_week:'Last 7 Days',last_month:'Last 30 Days',older:'30+ Days'};const dm={};data.forEach(i=>dm[i.recency]=i.count);const od=order.map(k=>({label:labels[k],value:dm[k]||0}));flasherCharts.recency=new Chart(ctx,{type:'bar',data:{labels:od.map(i=>i.label),datasets:[{label:'Users',data:od.map(i=>i.value),backgroundColor:['#48bb78','#4299e1','#ed8936','#a0aec0']}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,grid:{color:'#e2e8f0'},ticks:{precision:0}},x:{grid:{display:false}}}}})}
function renderFlErrorTable(errors){const tb=document.querySelector('#fl-error-table tbody');tb.innerHTML='';if(errors.length===0){tb.innerHTML='<tr><td colspan="5" style="text-align:center;color:#a0aec0">No errors recorded</td></tr>';return}errors.forEach(e=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${escHtml(e.error_message||'Unknown')}</td><td>${escHtml(e.board||'-')}</td><td>${escHtml(e.version||'-')}</td><td class="error-text">${e.count}</td><td>${new Date(e.last_occurred).toLocaleString('en-GB')}</td>`;tb.appendChild(tr)})}
async function editProduct(pid){try{const p=await storeApi('/api/inventory/'+encodeURIComponent(pid));document.getElementById('edit-product-id').value=p.product_id;document.getElementById('edit-product-name').value=p.product_name||'';document.getElementById('edit-product-sku').value=p.sku||'';document.getElementById('edit-product-price').value=p.price||0;document.getElementById('edit-product-short-desc').value=p.short_description||'';document.getElementById('edit-product-long-desc').value=p.long_description||'';document.getElementById('edit-product-desc').value=p.description||'';document.getElementById('edit-product-image').value=p.image_url||'';document.getElementById('edit-product-stock').value=p.stock_quantity||0;document.getElementById('edit-product-threshold').value=p.low_stock_threshold||5;document.getElementById('edit-product-error').textContent='';currentEditImages=JSON.parse(p.images||'[]');renderEditImageGallery();document.getElementById('edit-product-modal').classList.add('open')}catch(e){alert('Failed to load product: '+e.message)}}

function renderEditImageGallery(){const g=document.getElementById('edit-img-gallery');const cnt=document.getElementById('edit-img-count');cnt.textContent='('+currentEditImages.length+'/8)';if(currentEditImages.length===0){g.innerHTML='<div style="color:#a0aec0;font-size:13px">No images uploaded</div>';return}g.innerHTML=currentEditImages.map((key,i)=>'<div class="img-thumb"><img src="'+STORE_API+'/images/'+key+'"><button class="img-delete" onclick="deleteProductImage('+i+')">&times;</button>'+(i===0?'<span class="img-badge">Main</span>':'')+'</div>').join('')}
async function uploadProductImage(){const pid=document.getElementById('edit-product-id').value;const file=document.getElementById('edit-img-file').files[0];const status=document.getElementById('edit-img-status');if(!file)return;if(currentEditImages.length>=8){status.textContent='Maximum 8 images';status.style.color='#e53e3e';return}status.textContent='Uploading...';status.style.color='#4299e1';const fd=new FormData();fd.append('image',file);try{const r=await fetch(STORE_API+'/api/inventory/'+encodeURIComponent(pid)+'/images',{method:'POST',headers:{'Authorization':'Bearer '+adminToken},body:fd});const d=await r.json();if(d.error){status.textContent=d.error;status.style.color='#e53e3e';return}currentEditImages.push(d.key);renderEditImageGallery();status.textContent='Uploaded';status.style.color='#48bb78';document.getElementById('edit-img-file').value=''}catch(e){status.textContent='Failed: '+e.message;status.style.color='#e53e3e'}}
async function deleteProductImage(index){const pid=document.getElementById('edit-product-id').value;if(!confirm('Delete this image?'))return;try{const r=await storeApi('/api/inventory/'+encodeURIComponent(pid)+'/images/'+index,'DELETE');if(r.error){alert(r.error);return}currentEditImages.splice(index,1);renderEditImageGallery()}catch(e){alert('Failed: '+e.message)}}
function closeEditProductModal(){document.getElementById('edit-product-modal').classList.remove('open')}
async function saveEditProduct(){const pid=document.getElementById('edit-product-id').value;const err=document.getElementById('edit-product-error');err.textContent='';const data={product_name:document.getElementById('edit-product-name').value.trim(),sku:document.getElementById('edit-product-sku').value.trim()||null,price:parseFloat(document.getElementById('edit-product-price').value)||0,short_description:document.getElementById('edit-product-short-desc').value.trim()||null,long_description:document.getElementById('edit-product-long-desc').value.trim()||null,description:document.getElementById('edit-product-desc').value.trim()||null,image_url:document.getElementById('edit-product-image').value.trim()||null,stock_quantity:parseInt(document.getElementById('edit-product-stock').value)||0,low_stock_threshold:parseInt(document.getElementById('edit-product-threshold').value)||5,reason:'Product edit'};if(!data.product_name){err.textContent='Name is required';return}try{const r=await storeApi('/api/inventory/'+encodeURIComponent(pid),'PUT',data);if(r.error){err.textContent=r.error;return}closeEditProductModal();loadInventory()}catch(e){err.textContent='Failed: '+e.message}}
async function archiveProduct(pid,restore){const action=restore?'restore':'archive';if(!confirm('Are you sure you want to '+action+' this product?'))return;try{const r=await storeApi('/api/inventory/'+encodeURIComponent(pid)+'/archive','POST',{active:!!restore});if(r.error){alert(r.error);return}loadInventory()}catch(e){alert('Failed: '+e.message)}}
async function deleteProduct(pid,name){if(!confirm('Permanently delete '+name+'? This cannot be undone.'))return;try{const r=await storeApi('/api/inventory/'+encodeURIComponent(pid),'DELETE');if(r.error){alert(r.error);return}loadInventory()}catch(e){alert('Failed: '+e.message)}}
function filterEmails(type,btn){currentEmailFilter=type;document.querySelectorAll('#section-emails .filter-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');loadEmails()}
async function loadEmails(){const ld=document.getElementById('emails-loading'),tb=document.getElementById('emails-table'),em=document.getElementById('emails-empty');ld.style.display='block';tb.style.display='none';em.style.display='none';try{let p='';if(currentEmailFilter)p=`?type=${currentEmailFilter}`;const d=await storeApi(`/api/emails${p}`);const emails=d.emails||[];ld.style.display='none';if(emails.length===0){em.style.display='block';return}tb.style.display='table';const bd=document.getElementById('emails-body');bd.innerHTML='';emails.forEach(e=>{const tr=document.createElement('tr');const dt=new Date(e.created_at).toLocaleString('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});const typeLabels={confirmation:'Confirmation',shipped:'Shipped',tracking:'Tracking',refund:'Refund',comment:'Comment',return_label:'Return Label',unknown:'Unknown'};const statusCls=e.status==='sent'?'status-sent':e.status==='failed'?'status-failed':'status-skipped';tr.innerHTML=`<td>${dt}</td><td><span class="email-type-badge email-type-${e.email_type}">${typeLabels[e.email_type]||e.email_type}</span></td><td>${escHtml(e.recipient)}</td><td>${escHtml(e.subject)}</td><td>${e.invoice_number?'<strong>'+escHtml(e.invoice_number)+'</strong>':'-'}</td><td><span class="status-badge ${statusCls}">${e.status.charAt(0).toUpperCase()+e.status.slice(1)}</span>${e.error?'<div style="font-size:11px;color:#e53e3e;margin-top:2px">'+escHtml(e.error)+'</div>':''}</td>`;bd.appendChild(tr)})}catch(e){ld.innerHTML=`<div class="error-text">Failed to load emails: ${e.message}</div>`}}
function formatStatus(s){return{new:'New',label_created:'Label Created',shipped:'Shipped',completed:'Completed',cancelled:'Cancelled',refunded:'Refunded'}[s]||s}
function escHtml(s){if(!s)return'';const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function countryFlag(c){if(!c||c.length!==2)return'';const cp=[...c.toUpperCase()].map(x=>0x1F1E6-65+x.charCodeAt(0));return String.fromCodePoint(...cp)}

